### ISSUE TITLE
Image does not animate correctly

### ISSUE THREAD

**Issue by MarjanBasiri** [wxxsw/GSImageViewerController#14]
Hello, and thanks for this library.
I have implemented GSImageView exactly as you do:

```
let imageInfo   = GSImageInfo(image: image, imageMode: .aspectFit)
let transitionInfo = GSTransitionInfo(fromView: (self?.view)!)
let imageViewer = GSImageViewerController(imageInfo: imageInfo, transitionInfo: transitionInfo)                                imageViewer.dismissCompletion = {
       print("dismissCompletion")
}
self?.present(imageViewer, animated: true, completion: nil)
```

but, my image animating is not smooth at all.
and it does not get back to initial size by just tapping on it, and I need to pull it away to get the initial presentation of my image. 

I am using GSImage on a CollectionVeiwCell Image (and the collection view is implemented in a tableViewCell) (Using its tapGesture feature).
But you have used "Button".
and I can not use button.

**Comment by MarjanBasiri** [comment]
I have checked it, and I realized that the problem is using UIImage instead of Button.

Would you please add UIImage to use into your library?

**Comment by wxxsw** [comment]
Sorry, I may not understand what you mean.

I want to explain the features of the related features to see if it helps you:

1. fromView can receive any UIView subclass, whether it is a UIButton or a UIImageView
2. GSTransitionInfo can also be initialized with fromRect, which receives a CGRect, you can calculate the initial position of the view on the screen and pass in
3. imageMode supports aspectFit and aspectFill, which can set the final fill mode.

I think if you like, you can record a screen or provide a Demo to explain your problem. My email address is i@gesen.me.

**Comment by MarjanBasiri** [comment]
Thank you.
I have sent you a short video. In this video you'll see that the image motion is not smooth.

**Comment by wxxsw** [comment]
The reason is that the wrong control is used as a parameter to fromView and the problem is closed.

**Comment by MarjanBasiri** [comment]
Hello Gesen,

I have a problem again.
I have a wide image, and with GSImage I am using .aspectFit mode, but in
your pod, when I use .aspectFit, the motion wont be smooth.

Here is what I need:
1. .aspectFit Option (To show my wide image full screen),
2. A motion exactly like what we see in .aspectFill mode in your pod.

Thank you for your consideration.
