### ISSUE TITLE
Not Compatible with Swift 4.2

### ISSUE THREAD

**Issue by StellarKuldeep** [wxxsw/GSImageViewerController#15]
After updating xCode to 10.0 with Swift 4.2 gives errors but while I set **Swift Language Version** to **4.0** it works but with **4.2** it doesn't work.

How to fix this?

Thanks in Advance.

**Comment by JTP3XP** [comment]
The code currently uses the now (as of Swift 4.2) obsolete UIViewContentMode. You can take Xcode's suggestion to edit the code, or leave the build settings for the GSImageViewerController target to stay at 4.0 and wait for @wxxsw to update the code, even if the rest of your workspace is using 4.2.

![swifttarget40](https://user-images.githubusercontent.com/12720546/45932173-7bc62800-bf46-11e8-8b45-1219aff13fb7.png)

**Comment by wxxsw** [comment]
You can add this code to the last line of the `Podfile` and execute `pod install`:
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == 'GSImageViewController'
                config.build_settings['SWIFT_VERSION'] = '4.0'
            else
                config.build_settings['SWIFT_VERSION'] = '4.2'
            end
        end
    end
end
```
I will upgrade all my open source projects when I have time, thank you.

**Comment by wxxsw** [comment]
Please update the new version 1.5.1
