### ISSUE TITLE
May zoom multiple images, and change them on swipe.

### ISSUE THREAD

**Issue by string-aarzoo** [wxxsw/GSImageViewerController#19]

**Comment by wxxsw** [comment]
Although this feature is very common, I have not had time to add this feature recently.

**Comment by NikhilGangurde** [comment]
@wxxsw any update on this feature.
By the way thanks for Great repo.

**Comment by wxxsw** [comment]
Hi there,

In the future I will update more libraries related to SwiftUI. In addition to fixing bugs, the UIKit library may not add new features.
