### ISSUE TITLE
There is an animation glitch when zooming from one contentMode to another

### ISSUE THREAD

**Issue by bernikovich** [wxxsw/GSImageViewerController#21]
I know it's not easy to implement, but older ObjC libraries have these functionality. Right now it doesn't look good when you zooming from scaleAspectFill, to GS.aspectFit. What do you think about this feature?

**Comment by Zandor300** [comment]
+1, I have a `UICollectionView` with a bunch of images (like the Photos app) that have square `UIImageViews` in aspectFill. When tapping them, I want them to go fullscreen using this lib in aspectFit. But now when tapping them, it's like they go to aspectFit in the source `UIImageView` and then zoom in. Same with zooming out, they go back to the source `UIImageView` to `aspectFit` and then switch to `aspectFill` after the transition is done.

**Comment by wxxsw** [comment]
This problem has been solved, and update to the new version `1.6.1`.
