### ISSUE TITLE
open image in Landscape mode while all app screens in portrait mode. 

### ISSUE THREAD

**Issue by Mohamed-Ramadan** [wxxsw/GSImageViewerController#28]
My app screens all displayed in portrait view, but i need the images to be opened in landscape Or portrait view. can you add this option?

**Comment by wxxsw** [comment]
You can inherit GSImageViewerController and try to modify it, I may not be able to support this.

**Comment by Mohamed-Ramadan** [comment]
Thank you @wxxsw  for your suggestion, I did subclassing GSImageViewerController and force landscape rotation mode in viewWillAppear(), then force it again to portrait in viewWillDisappear().
