### ISSUE TITLE
Detect dismission

### ISSUE THREAD

**Issue by ArturGasparyan** [wxxsw/GSImageViewerController#7]
Hi

I would like to hide the status bar before presenting the image (which is easily done) but I fail to detect the moment when GSImageViewerController has been dismissed again, in order to show the status bar again. I had to edit your files...

Is there a way to detect it? I was not able to do so by using viewDidAppear by any presenting viewControllers nor by using dismiss(animated...), which is simply not called on the presenting viewController...

Any ideas? Help would be appreciated!

Thanks!

**Comment by wxxsw** [comment]
Thanks for your question, I added a new tag `1.4.1` and this callback:
```swift
imageViewer.dismissCompletion = {
    print("dismissCompletion")
}
```

**Comment by ArturGasparyan** [comment]
That was really fast! Thank you!
