### ISSUE TITLE
Image not center when zooming

### ISSUE THREAD

**Issue by DineshBhandari** [wxxsw/GSImageViewerController#8]
Image going beyond bounds of scroll view visible frame vertically.

**Comment by DineshBhandari** [comment]
While zooming the image inside the scrollView, image gets scrolled vertically and the scrollview height is much more greater than the height of image. Black space appearing.

**Comment by wxxsw** [comment]
I'm sorry, because I was very busy recently and could not solve the problem. If you can solve this problem, I will welcome Pull Requests.

**Comment by wxxsw** [comment]
Sorry, I have ignored this question for too long. If necessary, can reopen.
