### ISSUE TITLE
NSAttachments in UITextView

### ISSUE THREAD

**Issue by ArturGasparyan** [wxxsw/GSImageViewerController#9]
Hi!

I'm detecting a tap on an NSAttachment (image) inside a UITextView and open the image with your GSImageViewerController. Works great!

Only problem, I have to provide a TransitionInfo from view, and the only view I can give you is the UITextView itself. This means, when dismissing the image it animates to the size of the UITextView and then suddenly disappears. This is noticeable because the image (NSAttachment) is smaller in size than the UITextView.

Do you have any ideas how to make this smooth? I'm not sure if I can get a CGRect from the attachment, but I think yes. Maybe I could give you a TransitionInfo with a CGRect including a reference view to use as the anchor for your animation?

Thanks!

**Comment by wxxsw** [comment]
hi, I added a new initialization method `init(fromRect: CGRect)` to `GSTransitionInfo`, which you can use to do your work, and I release the new version `1.4.2`.

**Comment by ArturGasparyan** [comment]
Perfect!
